### ISSUE TITLE
🛑 Tuan Duc Design is down

### ISSUE THREAD

**Issue by tuanducdesign** [vnodesign/status#139]
In [`a532e98`](https://github.com/vnodesign/status/commit/a532e98cb80b9cdd8cefc9e9cf4415e4a7313d4c
), Tuan Duc Design (https://tuanducdesign.com) was **down**:
- HTTP code: 403
- Response time: 53 ms

**Comment by kimjoonja** [comment]
I can still access the website normally, why does it stop working?

![image-1](https://user-images.githubusercontent.com/35526029/232587719-2592540f-00e4-4e0d-95c5-0131d7bbf15a.png)

**Comment by tuanducdesign** [comment]
Ask team Upptime 😄
